spring:
  config:
    activate:
      on-profile: docker

  kafka:
    bootstrap-servers: kafka:29092

eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://ecommerce-discovery:8761/eureka

