spring.application.name: product-service
server.port: 0

spring:
  config:
    import:
      - classpath:/application-docker.yml
#      - classpath:/application-local.yml
#      - classpath:/application-prod.yml
#      - classpath:/application-secret.yml

  profiles:
    default: local

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

eureka:
  instance:
    hostname: localhost
    instance-id: ${spring.application.name}:${server.port}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka
