version: "3.8"
services:
  mysql:
    image: mysql:8.0
    networks:
      - ecommerce_network
    environment:
      - MYSQL_ROOT_PASSWORD=1234
    ports:
      - "3306:3306"
    volumes:
      - ./data/mysql_data:/var/lib/mysql
  
  redis:
    image: redis
    networks:
      - ecommerce_network
    ports:
      - "6379:6379"
    volumes:
      - ./data/redis_data:/data

#  ecommerce:
#    image: e-commerce:0.0.2
#    networks:
#      - ecommerce_network
#    ports:
#      - "8080:8080"
#    depends_on:
#      - mysql
#      - redis

networks:
  ecommerce_network:
    driver: bridge
