spring.application.name: e-commerce

spring:
  config:
    import:
      - classpath:/application-local.yml
      - classpath:/application-prod.yml

  profiles:
    default: local

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
