spring.application.name: member-service
server.port: 8081

spring:
  config:
    import:
      - classpath:/application-local.yml
      - classpath:/application-prod.yml
      - classpath:/application-secret.yml

  profiles:
    default: local

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

eureka:
  instance:
    instance-id: ${spring.application.name}:${server.port}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka

management:
  tracing:
    sampling:
      probability: 1.0
    propagation:
      consume: b3
      produce: b3_multi
  zipkin:
    tracing:
      endpoint: "http://localhost:9411/api/v2/spans"

logging:
  pattern:
    level: "%5p [%X{traceId:-},%X{spanId:-}]"

endpoints:
  web:
    exposure:
      include: refresh, health, beans, busrefresh, info, metrics, prometheus
