spring:
  config:
    activate:
      on-profile: docker

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://mysql-payment/e_commerce?useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 1234

  jpa:
    hibernate:
      ddl-auto: update

  kafka:
    bootstrap-servers: kafka:29092

eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://ecommerce-discovery:8761/eureka

aes:
  private:
    key: AES_PRIVATE_KEY_THIS_TEST_32BYTE

producers:
  topic1: payment_result
