spring:
  config:
    activate:
      on-profile: docker

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://mysql-product/e_commerce?useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 1234
    hikari:
      maximum-pool-size: 200
      minimum-idle: 10
      idle-timeout: 60000
      max-lifetime: 1800000
      connection-timeout: 30000

  jpa:
    hibernate:
      ddl-auto: update

  cache:
    type: redis
  data:
    redis:
      host: redis
      port: 6379

  kafka:
    bootstrap-servers: kafka:29092

aes:
  private:
    key: AES_PRIVATE_KEY_THIS_TEST_32BYTE

eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://ecommerce-discovery:8761/eureka

producers:
  topic1: product_result

consumers:
  topic1: product_request
  groupId: order
