spring.application.name: product-consumer
server.port: 0

spring:
  config:
    import:
      - classpath:/application-docker.yml
#      - classpath:/application-local.yml
#      - classpath:/application-prod.yml
#      - classpath:/application-secret.yml

  profiles:
    default: local

eureka:
  instance:
    instance-id: ${spring.application.name}:${random.value}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka
