spring.application.name: payment-service
server.port: 0

spring:
  config:
    import:
      - classpath:/application-local.yml
      - classpath:/application-prod.yml
      - classpath:/application-secret.yml

  profiles:
    default: local
