server:
  port: 8000

eureka:
  instance:
    instance-id: ${spring.application.name}:${server.port}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka


spring.application.name: gateway-service

spring:
  config:
    import:
      - classpath:/application-route.yml
      - classpath:/application-secret.yml
