spring.application.name: gateway-service

server:
  port: 8000

spring:
  config:
    activate:
      on-profile: docker

eureka:
  instance:
    instance-id: ${spring.application.name}:${server.port}
    hostname: localhost
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://ecommerce-discovery:8761/eureka

jwt:
  app:
    jwtSecretKey: vjyISXRhB2apE6e1OeOzM6r6oHNOkfT2/Lxt8sR6GjCrKl7B1aGzKzmwTejI1D6m

---
spring:
  cloud:
    gateway:
      default-filters:
        - name: GlobalFilter
          args:
            baseMessage: Spring Cloud Gateway GlobalFilter.
            preLogger: true
            postLogger: true
      routes:
        - id: member-service
          uri: lb://MEMBER-SERVICE
          predicates:
            - Path=/email/** # 인증필요X
            - Method=POST
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/(?<segment>.*), /$\{segment}
        - id: product-service
          uri: lb://PRODUCT-SERVICE
          predicates:
            - Path=/products/** # 인증필요X
            - Method=GET
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/(?<segment>.*), /$\{segment}
        - id: member-service
          uri: lb://MEMBER-SERVICE
          predicates:
            - Path=/auth/signup # 인증필요X
            - Method=POST
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/(?<segment>.*), /$\{segment}
        - id: member-service
          uri: lb://MEMBER-SERVICE
          predicates:
            - Path=/auth/login # 인증필요X
            - Method=POST
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/(?<segment>.*), /$\{segment}
        - id: member-service
          uri: lb://MEMBER-SERVICE
          predicates:
            - Path=/auth/** # 인증필요O
            - Method=GET, POST, PUT, DELETE
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/(?<segment>.*), /$\{segment}
            - AuthorizationHeaderFilter
        - id: member-service
          uri: lb://MEMBER-SERVICE
          predicates:
            - Path=/carts/** # 인증필요O
            - Method=GET, POST, PUT, DELETE
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/(?<segment>.*), /$\{segment}
            - AuthorizationHeaderFilter
        - id: order-service
          uri: lb://ORDER-SERVICE
          predicates:
            - Path=/order/** # 인증필요O
            - Method=GET, POST, PUT, DELETE
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/(?<segment>.*), /$\{segment}
            - AuthorizationHeaderFilter
        - id: delivery-service
          uri: lb://DELIVERY-SERVICE
          predicates:
            - Path=/delivery/** # 인증필요O
            - Method=GET, POST, PUT, DELETE
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/(?<segment>.*), /$\{segment}
            - AuthorizationHeaderFilter
        - id: payment-service
          uri: lb://PAYMENT-SERVICE
          predicates:
            - Path=/payment/** # 인증필요O
            - Method=GET, POST, PUT, DELETE
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/(?<segment>.*), /$\{segment}
            - AuthorizationHeaderFilter
        - id: product-service
          uri: lb://PRODUCT-SERVICE
          predicates:
            - Path=/products/** # 인증필요O
            - Method=POST, PUT, DELETE
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/(?<segment>.*), /$\{segment}
            - AuthorizationHeaderFilter
